### PR TITLE
Use Pooch for downloads

### PR DESCRIPTION
**Pull request by rabernat**
This PR updates the example notebooks to use [Pooch](https://www.fatiando.org/pooch/latest/index.html) for downloading the data. This is better than requests because it is
- more transparent where the data are coming from (download via DOI)
- uses memory more efficiently (streams the file to disk)
- includes md5 checksum verification

### CODE REVIEW

**Comment by NoraLoose** [comment]
For some reason my comments on the `review-notebook` app are not showing up here, so I'm reposting the main one here.

When I run the cell
```
import pooch

fname = pooch.retrieve(
    url="doi:10.6084/m9.figshare.14575356.v1/Global_U_SSH.nc",
    known_hash="md5:f98b5f2d1f3ccef5685851519481b2da",
)
```
I get the error
```
ValueError: Unrecognized URL protocol 'doi' in 'doi:10.6084/m9.figshare.14575356.v1/Global_U_SSH.nc'. Must be one of dict_keys(['ftp', 'https', 'http', 'sftp']).
```

**Comment by rabernat** [comment]
To get the DOI resolving you need to be on Pooch >= [1.5.0](https://github.com/fatiando/pooch/releases/tag/v1.5.0). (#118 is closely related to this!)

**Comment by NoraLoose** [comment]
Thanks, it worked for me with `Pooch >= 1.5.0.`. Mapping out all required packages + versions for the example notebooks, as suggested in #118, will be super useful.

Since the comments from the `review-notebook` are not showing up, I'm posting them here:

- `docs/examples/example_numerical_instability.ipynb`: we can remove 
```
import requests
```
in the first cell
- `docs/examples/example_tripole_grid.ipynb`: toward the end of the notebook there is an extra section ("Global MOM6 data") where new data is pulled. Here we need to substitute requests by pooch, too.
- `docs/gpu.ipynb`: same here (could potentially move this notebook to `docs/examples/`)

**Comment by rabernat** [comment]
Thanks for catching those issues! Will try to update within a few days.

**Comment by NoraLoose** [comment]
I can also just push these three requested changes to this branch. Let me know if you prefer this. (I have some time tomorrow and Friday.) I'd like this PR merged first before getting to some of the other PRs / issues to avoid conflicts.

**Comment by rabernat** [comment]
Sure, that would be great. Thanks Nora! As usual my ambitions exceed my available time to work on the project.

**Comment by NoraLoose** [comment]
I just pushed an update:
* all notebooks now use pooch for download
* I inserted `%%time` for all cells that take longer than 10sec to run (this was @isgiddy's suggestion over [here](https://github.com/openjournals/joss-reviews/issues/3947#issuecomment-991701514) in the JOSS review)

Before we merge this PR I would like to solve issue #122 and then re-run the tripole grid example notebook. As of now, this notebook is broken (see #122).

**Review by NoraLoose — APPROVED** [review]
This PR is ready to be merged. All example notebooks use pooch, and the tripole example notebook is fixed (thanks to #123).

**Pull request merged**
