### PR TITLE
Setting up the docs with ReadTheDocs

### LINKED ISSUE #7: create documentation stub
We need to set up a simple sphinx documentation site and set it up to build automatically with readthedocs.

@jbusecke, I will assign this to you once you accept the invite to join this repo.

### LINKED ISSUE #13: Consolidating configs in `pyproj.toml`
According to the [isort docs](https://pycqa.github.io/isort/docs/configuration/options/#example-pyprojecttoml) we can specify the options in `.isort.cfg` also in `pyproj.toml`, leaving us with less files.

Ill submit a PR once #11 is merged.

### PR DESCRIPTION
**Pull request by jbusecke**
I have set up a dummy doc folder that is built as part of the CI each time a Pull Request is made. 

- [x] Closes #7 
- [x] Closes #13

### CODE REVIEW

**Comment by jbusecke** [comment]
The RTD build is not triggered for this PR. I am not sure if it was right to set up RTD from my personal GH account?
I think this is basically an issue of authenticating RTD under `Applications` see [here](https://docs.readthedocs.io/en/latest/guides/autobuild-docs-for-pull-requests.html#troubleshooting). @rabernat could you check if you can connect it from the org side?

**Comment by rabernat** [comment]
If you set it up from your personal account, I think you will have to set up the webhook yourself.

Go to https://github.com/ocean-eddy-cpt/gcm-filters/settings/hooks

Then follow the instructions here:

https://docs.readthedocs.io/en/latest/webhooks.html#github

**Comment by rabernat** [comment]
A RTD build did run! https://readthedocs.org/projects/gcm-filters/builds/12748970/

But maybe not on the PR?

**Comment by rabernat** [comment]
bingo, had to enable PR builds on RTD

**Comment by jbusecke** [comment]
Nice! Thanks @rabernat. Ill finish this up now.

**Comment by jbusecke** [comment]
All right. I think this is good to go. Check the docs out here: https://gcm-filters--11.org.readthedocs.build/en/11/

**Comment by rabernat** [comment]
This is great Julius! Thanks so much!

**Pull request merged**
