### PR TITLE
use correct license classifier

### LINKED ISSUE #100: Release of 0.1.3 failed because of invalid LGPL license classifier
> Invalid value for classifiers. Error: Classifier 'License :: OSI Approved :: LGPL license' is not a valid classifier.

https://github.com/ocean-eddy-cpt/gcm-filters/runs/4112493366?check_suite_focus=true

The list of valid classifiers are here: https://pypi.org/classifiers/

This is an easy fix, but we may have to do another release (0.1.4) in order to get it out.

xref #96

### PR DESCRIPTION
**Pull request by rabernat**
fixes #100

### CODE REVIEW

**Comment by NoraLoose** [comment]
Thanks for the fix, Ryan!

**Comment by rabernat** [comment]
After this is merged, I'm going to see if I can delete the 0.1.3 release and do it again. If that fails, we will move to 0.1.4.

**Comment by NoraLoose** [comment]
Sorry about the mess 😬

**Comment by rabernat** [comment]
Not a big deal! We learned something. It's already fixed: https://pypi.org/project/gcm-filters/

**Pull request merged**
