### PR TITLE
First draft of JOSS Paper

### PR DESCRIPTION
**Pull request by NoraLoose**
We are making good progress on our [project board](https://github.com/ocean-eddy-cpt/gcm-filters/projects/1) with ticking off issues toward submitting the JOSS paper! 

`paper.md` includes a first draft of the paper - I'm happy to hear feedback and comments. `paper.pdf` is the compiled version. #47 includes a useful checklist for the paper.

Notes:
* The **author list** is still TBD. Maybe we can discuss in #44 how to handle the questions of authorship and contribution. (In general, we have agreed to follow a very open authorship model for the JOSS paper - this is a community effort and any contribution is valuable!)
*  The subsection on **Computational Efficiency** still needs to be filled. Maybe we can recap in #45 what we want to do on performance evaluation for the paper.

### CODE REVIEW

**Comment by NoraLoose** [comment]
JOSS also requires us to include the following in the paper:

* *Mention (if applicable) a representative set of past or ongoing research projects using the software and recent scholarly publications enabled by it.*

Do you think that mentioning the ongoing CPT work will be sufficient? Any other projects/work that we could mention?

**Comment by ElizabethYankovsky** [comment]
@NoraLoose regarding relating the ongoing CPT work -- I have a notebook/tutorial on how to apply GCM-filters to performing the combined spatial and temporal filtering that I've mentioned in the past. The goal was to have a spatial filter that would create a consistent filter scale across the various resolutions of NW2. I initially had trouble applying the package to do this because of lack of convergence at large filter scales that were several times the local deformation radius (which I think is physically relevant when we want to filter out mesoscale eddies). I eventually got this working by coarsening to 1/4 degree and then performing the filtering. I know Hemant already contributed a tutorial where he demonstrated how to coarsen/filter, but I'd be happy to share what I've done in NeverWorld2 as another example of filtering on a non-uniform and large filter scale related to the deformation radius (if it doesn't overlap with what's already been included).

**Comment by iangrooms** [comment]
> JOSS also requires us to include the following in the paper:
> 
>     * _Mention (if applicable) a representative set of past or ongoing research projects using the software and recent scholarly publications enabled by it._
> 
> 
> Do you think that mentioning the ongoing CPT work will be sufficient? Any other projects/work that we could mention?

We can cite the paper on essoar.

**Comment by hmkhatri** [comment]
@NoraLoose Thanks. I am also using gcm-filters for vorticity budget analysis in global models. There is no manuscript to cite as the work is in the early stage.

**Comment by NoraLoose** [comment]
@ElizabethYankovsky I guess my question was more directed at published/citable work that we could list in a subsection of the JOSS paper. (I think this is what the JOSS requirement means.) So citing the JAMES gcm-filters paper, led by Ian, would be a good option. 

But independent of that, more examples for the documentation are always welcome! The documentation already has [an example](https://gcm-filters.readthedocs.io/en/latest/tutorial_filter_types.html), in which NeverWorld2 data is filtered to the spatially-varying deformation radius. And we have Hemant's [coarsening/filtering tutorial](https://gcm-filters.readthedocs.io/en/latest/tutorial_numerical_instability.html) as well. But I'm sure your example would add something new! Alternatively, an example with MOM5 data (like for the JAMES paper) would be great too. But just to be clear, none of these would be essential for moving forward with the JOSS paper I think.

**Comment by rabernat** [comment]
FWIW, I don't think we should let the performance enhancements being discussed in #45 hold up the JOSS submission.

**Comment by NoraLoose** [comment]
Thanks for your comment, @rabernat! I agree. Refactoring the package to use numba for a performance improvement would be really valuable, but it will take some time. I think it makes sense to submit the JOSS paper soon. 

Do we still want to document the current performance, for example with a figure like you posted [here](https://github.com/ocean-eddy-cpt/gcm-filters/issues/45#issuecomment-884297536)? I think this could be an interesting addition to the paper and/or the documentation.

PS: Any idea why `paper.md`, `paper.pdf`, `paper.bib`, and `filtered_vorticity.png` didn't make it to the master branch even though you merged this PR?

**Comment by rabernat** [comment]
I am very confused. I don't actually remember merging this. I did merge #78. Something weird is going on.

**Comment by rabernat** [comment]
Ok, I think I know what happened. I think you started working on #78 from a branch that already included 75cb16f17a6111864242beea3d0c3e0f512f8fee (the final commit in this PR). So when we merged #78, this PR was automatically considered merged as well, even though no one clicked "merge."

However, #78 went on to include more commits such as https://github.com/ocean-eddy-cpt/gcm-filters/commit/53fbb5425095f4b6329bed6774dd5f914bcf18c5, which explicitly removed those files. That's why they are not appearing.

We have two options:
- Do fancy git rebasing / cherry-picking to remove those `rm` commits from the master branch history
- Just add the files again via a new PR (starting from current master)

**Comment by NoraLoose** [comment]
Sorry about the mess. Not sure what I did there. Anyway, I just opened a new PR that adds the same files.

**Pull request merged**
