### PR TITLE
Switch RTD build to mamba

### PR DESCRIPTION
**Pull request by jbusecke**
Towards addressing problems in #120

### CODE REVIEW

**Comment by jbusecke** [comment]
So if I comment out [these lines](https://github.com/ocean-eddy-cpt/gcm-filters/blob/efa9be18bd3d02939d4926209f09b2e070854fcb/readthedocs.yml#L16-L17) the build succeeds. I am kind of confused why this would have not been an issue before switching to mamba. 

Apparently [I](https://github.com/ocean-eddy-cpt/gcm-filters/blame/75f172c7c74c1f2f3b91e36f7345bd138f01c881/readthedocs.yml#L9) put it in there a while ago, but if the docs look OK I would just remove it?

Could someone go through the [logs](https://readthedocs.org/api/v2/build/15698253.txt) and the [docs](https://gcm-filters.readthedocs.io/en/latest/) created for this PR and double check if the warnings can be ignored and if the docs look ok?

**Comment by NoraLoose** [comment]
Thanks for this PR @jbusecke! I checked the docs, and they look ok. I'm not sure about the warnings in the logs. Probably ok to ignore them(?)

**Comment by jbusecke** [comment]
I would say so for now. Since its not part of the actual code, the docs output is all that matters, right?

**Comment by NoraLoose** [comment]
Yes. I think we can merge this! 

Would you have time to work on #120 with me next? It would be great to get your input there!

**Comment by NoraLoose** [comment]
Thanks! I didn't mean today, just whenever you have a chance. Just asking because from what you wrote in #120 you think that mamba can help over there. :)

**Comment by jbusecke** [comment]
Oh yes absolutely! Sorry for the misinterpretation.

**Pull request merged**
