### PR TITLE
Tutorial on filtering on tripole grid

### LINKED ISSUE #1: Add MOM6 kernel
Right now we just have a trivial laplacian kernel:

https://github.com/ocean-eddy-cpt/gcm-filters/blob/7b8d2906d0bdacb98846f4e39c3883ed3a3fc44a/gcm_filters/kernels.py#L17-L22

We need to add the kernel for MOM6. This should be based on whatever @NoraLoose is actively using in her notebooks.

### LINKED ISSUE #53: Tutorial on filtering data on tripole grid
Show how the use of different Laplacians will
* **ignore** tripolar exchanges (`REGULAR_WITH_LAND` & `IRREGULAR_WITH_LAND`)
* **handle** tripolar exchanges (`TripolarRegularLaplacianTpoint` & `POPTripolarLaplacianTpoint`)

### PR DESCRIPTION
**Pull request by NoraLoose**
This adds a tutorial on how to filter data on global tripolar grids (and fixes #53). Specifically, this tutorial uses Laplacians of varying complexity and shows how they **handle/ignore the tripolar northern boundary condition**. So far, the tutorial operates on a tripolar POP grid. 

I am labeling this PR as *draft* because I think there is great potential to improve this tutorial. My idea is that we could use the exact same 4 Laplacians from the tutorial for **global MOM6 data**. This would be of value because:
1. Testing the tripolar Laplacians for MOM6 data would close #1. (I think nothing would have to be changed in the code, so if successful we should really rename the Laplacians from "POP tripolar Laplacians" to something more general.) If successful, we would have filters that work for *global* MOM6 data, maybe of interest for our global CPT simulations!? 😃 
2. The plots in the tutorial would benefit from being plotted on a polar NH stereographic projection (to actually recognize the Arctic!), but I had trouble doing this for the tripole POP grid. I saw that there may be some [shovel-ready scripts](https://mom6-tools.readthedocs.io/en/latest/examples/seaice.html) for plotting MOM6 tripole grid data on polar NH stereographic projections.

I am tagging @gustavo-marques, @sdbachman and @hmkhatri here. Let me know if you (or anyone else) are interested in testing the tripolar Laplacians for global MOM6 data, and potentially in expanding this tutorial with some global MOM6 examples. No pressure of course. :)

### CODE REVIEW

**Comment by NoraLoose** [comment]
PS: This plot summarizes some of the plotting issues I am having with the POP tripole data in the Arctic. 

POP_Arctic_plotting_issues

**Comment by hmkhatri** [comment]
@NoraLoose Thanks for the tutorial. I can try your script with MOM6 data.

**Comment by sdbachman** [comment]
@hmkhatri Do you want to test this, or should @gustavo-marques and I give it a try?

**Comment by hmkhatri** [comment]
@sdbachman Sorry, did not get a chance to look at this. I will try to do it this week. 
It is ok if @gustavo-marques wants to try this tutorial in the meanwhile.

**Comment by hmkhatri** [comment]
@NoraLoose I tried your tutorial with MOM6 data (with fixed scale_factor and Gaussian kernel). The two algorithms (with or without different handling of the tripolar grid) give different answers on a horizontal line passing through the pole. Otherwise, there are no differences. Does it look good?

image

The link to the ipython notebook is 
https://github.com/hmkhatri/gcm-filters/blob/tutorial-tripole/docs/tutorial_tripole_grid.ipynb

**Comment by sdbachman** [comment]
@hmkhatri Is there anything special about that particular line through the pole?   Is that perhaps the boundary of the northernmost set of tiles?

**Comment by hmkhatri** [comment]
@sdbachman In MOM6 output, longitude limits are (-300, 60). The line passing through the pole in the figure above is this boundary. I guess the gcm-filters is not treating it as a periodic boundary.

**Comment by NoraLoose** [comment]
@hmkhatri, thanks for testing this. Yes, the **only** differences between the two Laplacians/filters should be along the tripolar seam line in the Arctic as you found.

We could try to filter a field with some smaller-scale structure in the Arctic (maybe Atlantic water temperature somewhere between 300m and 700m depth)? Then the field filtered with the `Regular` Laplacian should have some artifacts along the tripole seam line because the tripole seam line is treated like a continental boundary by this Laplacian. The field filtered with the `Tripolar` Laplacian should look nice and smooth.

**Comment by hmkhatri** [comment]
@NoraLoose I did a test on the surface vorticity field, which has a small-scale structure. There is no difference between the two methods except for the signal along the horizontal line, which is the longitudinal boundary of the model grid. The difference is now enhanced. Shall I add this example and make a pull request to your notebook? 

image

**Comment by NoraLoose** [comment]
@hmkhatri great! Yes, I think your example would be a very nice addition to the tutorial. Would you want to submit a PR to `NoraLoose:tutorial-tripole-grid`? Thanks!

**Comment by hmkhatri** [comment]
@NoraLoose Submitted a PR `NoraLoose:tutorial-tripole-grid`. Let me know if changes are required.

**Review by iangrooms — COMMENTED** [review]
This looks good to me. If you can get it to pass pre-commit then I think it would be fine to merge.

**Review by rabernat — APPROVED** [review]
Really nice notebook.

**Comment by NoraLoose** [comment]
Thanks for the reviews, @iangrooms and @rabernat! Pre-commit is now passing, so I think we can merge.

**Pull request merged**
